import { Analytics } from '@vercel/analytics/next';
import type { Metadata, Viewport } from 'next';
import './globals.css';
import { siteConfig } from '@/lib/site-config';
import { Toaster } from '@/components/ui/toast';

const siteTitle =
  'Bandi — Zero commission bike, auto and car rides launching August 15';
const siteDescription =
  'Bandi is launching August 15 with zero ride commission, one month free subscription for approved drivers, no surge for riders, direct driver payment, and verified bike, auto, hatchback, sedan, premium and XL rides with live tracking and safety tools.';
const siteUrl = siteConfig.siteUrl;
const previewImage = '/bandi-app-icon.png';

export const metadata: Metadata = {
  applicationName: siteConfig.brandName,
  title: {
    default: siteTitle,
    template: `%s | ${siteConfig.brandName}`,
  },
  description: siteDescription,
  generator: 'Bandi',
  metadataBase: new URL(siteUrl),
  keywords: [
    'Bandi',
    'Bandi Mobility',
    'ride booking app',
    'city ride booking app',
    'taxi booking app',
    'bike taxi app',
    'bike ride app',
    'bike rides India',
    'auto booking app',
    'auto rickshaw booking app',
    'auto rides India',
    'cab booking app',
    'car rides India',
    'hatchback rides',
    'sedan rides',
    'premium car rides',
    'XL rides',
    'airport rides',
    'driver first mobility',
    'driver app India',
    'rider app India',
    'August 15 launch',
    'one month free driver subscription',
    'no surge rides',
    'no surge pricing',
    'zero commission rides',
    'zero commission driver app',
    'direct driver payment',
    'direct UPI payment rides',
    'verified drivers',
    'live ride tracking',
    'ride safety app',
    'SOS ride safety',
    'driver keeps 100 percent fare',
    'fair fare rides',
    'India mobility app',
    'Bandi Mobility Private Limited',
    'Hyderabad mobility app',
    'Bandi Mobility Hyderabad',
    'Bandi Mobility India',
    'Bandi Mobility Telangana',
    'Bandi Mobility Andhra Pradesh',
    'Bandi Mobility Karnataka',
    'Bandi Mobility Tamil Nadu',
    'Bandi Mobility Maharashtra',
    'Bandi Mobility Delhi',
    'Bandi Mobility Bengaluru',
    'Bandi Mobility Chennai',
    'Bandi Mobility Mumbai',
    'Bandi Mobility Pune',
    'Bandi Mobility Warangal',
    'Hyderabad bike rides',
    'Hyderabad auto rides',
    'Hyderabad car rides',
    'Hyderabad hatchback rides',
    'Hyderabad sedan rides',
    'Hyderabad premium car rides',
    'Hyderabad XL rides',
    'Hyderabad airport rides',
    'Hyderabad driver app',
    'Hyderabad rider app',
    'Hyderabad ride booking app',
    'Hyderabad bike taxi app',
    'Hyderabad auto rickshaw booking app',
    'Hyderabad cab booking app',
    'Hyderabad mobility app',
    'Hyderabad ride safety app',
    'Hyderabad SOS ride safety',
    'Hyderabad fair fare rides',
    'Hyderabad verified drivers',
    'Hyderabad direct driver payment',
    'Hyderabad direct UPI payment rides',
    'Hyderabad zero commission rides',
    'Hyderabad zero commission driver app',
    'Hyderabad no surge rides',
    'Hyderabad no surge pricing',
    'Hyderabad one month free driver subscription',
    'Hyderabad August 15 launch',
    'Hyderabad Bandi Mobility Private Limited',
    'Hyderabad Bandi Mobility',
    'Warangal bike rides',
    'Warangal auto rides',
    'Warangal car rides',
    'Warangal hatchback rides',
    'Warangal sedan rides',
    'Warangal premium car rides',
    'Warangal XL rides',
    'Warangal airport rides',
    'Warangal driver app',
    'Warangal rider app',
    'Warangal ride booking app',
    'Warangal bike taxi app',
    'Warangal auto rickshaw booking app',
    'Warangal cab booking app',
    'Warangal mobility app',
    'Warangal ride safety app',
    'Warangal SOS ride safety',
    'Warangal fair fare rides',
    'Warangal verified drivers',
    'Warangal direct driver payment',
    'Warangal direct UPI payment rides',
    'Warangal zero commission rides',
    'Warangal zero commission driver app',
    'Warangal no surge rides',
    'Warangal no surge pricing',
    'Warangal one month free driver subscription',
    'Bangalore bike rides',
    'Bangalore auto rides',
    'Bangalore car rides',
    'Bangalore hatchback rides',
    'Bangalore sedan rides',
    'Bangalore premium car rides',
    'Bangalore XL rides',
    'Bangalore airport rides',
    'Bangalore driver app',
    'Bangalore rider app',
    'Bangalore ride booking app',
    'Bangalore bike taxi app',
    'Bangalore auto rickshaw booking app',
    'Bangalore cab booking app',
    'Bangalore mobility app',
    'Bangalore ride safety app',
    'Bangalore SOS ride safety',
    'Bangalore fair fare rides',
    'Bangalore verified drivers',
    'Bangalore direct driver payment',
    'Bangalore direct UPI payment rides',
    'Bangalore zero commission rides',
    'Bangalore zero commission driver app',
    'Bangalore no surge rides',
    'Bangalore no surge pricing',
    'Bangalore one month free driver subscription',
    'Mumbai bike rides',
    'Mumbai auto rides',
    'Mumbai car rides',
    'Mumbai hatchback rides',
    'Mumbai sedan rides',
    'Mumbai premium car rides',
    'Mumbai XL rides',
    'Mumbai airport rides',
    'Mumbai driver app',
    'Mumbai rider app',
    'Mumbai ride booking app',
    'Mumbai bike taxi app',
    'Mumbai auto rickshaw booking app',
    'Mumbai cab booking app',
    'Mumbai mobility app',
    'Mumbai ride safety app',
    'Mumbai SOS ride safety',
    'Mumbai fair fare rides',
    'Mumbai verified drivers',
    'Mumbai direct driver payment',
    'Mumbai direct UPI payment rides',
    'Mumbai zero commission rides',
    'Mumbai zero commission driver app',
    'Mumbai no surge rides',
    'Mumbai no surge pricing',
    'Mumbai one month free driver subscription',
    'Pune bike rides',
    'Pune auto rides',
    'Pune car rides',
    'Pune hatchback rides',
    'Pune sedan rides',
    'Pune premium car rides',
    'Pune XL rides',
    'Pune airport rides',
    'Pune driver app',
    'Pune rider app',
    'Pune ride booking app',
    'Pune bike taxi app',
    'Pune auto rickshaw booking app',
    'Pune cab booking app',
    'Pune mobility app',
    'Pune ride safety app',
    'Pune SOS ride safety',
    'Pune fair fare rides',
    'Pune verified drivers',
    'Pune direct driver payment',
    'Pune direct UPI payment rides',
    'Pune zero commission rides',
    'Pune zero commission driver app',
    'Pune no surge rides',
    'Pune no surge pricing',
    'Pune one month free driver subscription',
    'Chennai bike rides',
    'Chennai auto rides',
    'Chennai car rides',
    'Chennai hatchback rides',
    'Chennai sedan rides',
    'Chennai premium car rides',
    'Chennai XL rides',
    'Chennai airport rides',
    'Chennai driver app',
    'Chennai rider app',
    'Chennai ride booking app',
    'Chennai bike taxi app',
    'Chennai auto rickshaw booking app',
    'Chennai cab booking app',
    'Chennai mobility app',
    'Chennai ride safety app',
    'Chennai SOS ride safety',
    'Chennai fair fare rides',
    'Chennai verified drivers',
    'Chennai direct driver payment',
    'Chennai direct UPI payment rides',
    'Chennai zero commission rides',
    'Chennai zero commission driver app',
    'Chennai no surge rides',
    'Chennai no surge pricing',
    'Chennai one month free driver subscription',
    'Tirupati bike rides',
    'Tirupati auto rides',
    'Tirupati car rides',
    'Tirupati hatchback rides',
    'Tirupati sedan rides',
    'Tirupati premium car rides',
    'Tirupati XL rides',
    'Tirupati airport rides',
    'Tirupati driver app',
    'Vijayawada bike rides',
    'Vijayawada auto rides',
    'Vijayawada car rides',
    'Vijayawada hatchback rides',
    'Vijayawada sedan rides',
    'Vijayawada premium car rides',
    'Vijayawada XL rides',
    'Vijayawada airport rides',
    'Vijayawada driver app',
    'Vijayawada rider app',
    'Vijayawada ride booking app',
    'Vijayawada bike taxi app',
    'Vijayawada auto rickshaw booking app',
    'Vizag bike rides',
    'Vizag auto rides',
    'Vizag car rides',
    'Vizag hatchback rides',
    'Vizag sedan rides',
    'Vizag premium car rides',
    'Vizag XL rides',
    'Vizag airport rides',
    'Vizag driver app',
    'Vizag rider app',
    'Vizag ride booking app',
    'Vizag bike taxi app',
    'Vizag auto rickshaw booking app',
    'Vizag cab booking app',
    'Vizag mobility app',
    'Vizag ride safety app',
    'Vizag SOS ride safety',
    'Vizag fair fare rides',
    'Vizag verified drivers',
    'Vizag direct driver payment',
    'Vizag direct UPI payment rides',
    'Vizag zero commission rides',
    'Vizag zero commission driver app',
    'Vizag no surge rides',
    'Vizag no surge pricing',
    'Vizag one month free driver subscription',
  ],
  authors: [{ name: siteConfig.companyName, url: siteUrl }],
  creator: siteConfig.companyName,
  publisher: siteConfig.companyName,
  category: 'transportation',
  alternates: {
    canonical: '/',
    languages: {
      en: '/?lang=en',
      hi: '/?lang=hi',
      te: '/?lang=te',
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: siteUrl,
    siteName: siteConfig.brandName,
    title: siteTitle,
    description: siteDescription,
    images: [
      {
        url: previewImage,
        width: 1024,
        height: 1024,
        alt: `${siteConfig.brandName} app icon`,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteTitle,
    description: siteDescription,
    images: [previewImage],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  ...(siteConfig.iosAppId
    ? {
        appleWebApp: {
          capable: true,
          title: siteConfig.brandName,
          statusBarStyle: 'default' as const,
        },
        itunes: {
          appId: siteConfig.iosAppId,
        },
      }
    : {}),
  icons: {
    icon: [
      {
        url: '/favicon.ico',
        type: 'image/x-icon',
      },
      {
        url: '/icon.svg',
        type: 'image/svg+xml',
      },
      {
        url: '/icon.png',
        type: 'image/png',
      },
      {
        url: '/icon-light-32x32.png',
        media: '(prefers-color-scheme: light)',
      },
      {
        url: '/icon-dark-32x32.png',
        media: '(prefers-color-scheme: dark)',
      },
    ],
    shortcut: '/favicon-16x16.png',
    apple: '/apple-icon.png',
  },
};

export const viewport: Viewport = {
  colorScheme: 'light',
  themeColor: '#0ea5e9',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': `${siteUrl}/#organization`,
        name: siteConfig.companyName,
        alternateName: siteConfig.brandName,
        url: siteUrl,
        logo: `${siteUrl}/bandi-logo.png`,
        email: siteConfig.email,
        telephone: siteConfig.phone,
        address: siteConfig.address,
        sameAs: [siteConfig.iosAppUrl, siteConfig.androidAppUrl].filter(
          Boolean,
        ),
      },
      {
        '@type': 'WebSite',
        '@id': `${siteUrl}/#website`,
        name: siteConfig.brandName,
        url: siteUrl,
        publisher: { '@id': `${siteUrl}/#organization` },
        inLanguage: ['en', 'hi', 'te'],
      },
      {
        '@type': 'MobileApplication',
        name: siteConfig.brandName,
        applicationCategory: 'TravelApplication',
        operatingSystem: 'iOS, Android',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR' },
        publisher: { '@id': `${siteUrl}/#organization` },
      },
    ],
  };

  return (
    <html lang="en" className="bg-slate-50">
      <head>
        <meta
          name="google-site-verification"
          content="W8SMPrixyYhA-Awf9Csyet0Xmrf3wOWH6DfBWYeATP8"
        />
      </head>
      <body className="font-sans antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        {children}
        {process.env.NODE_ENV === 'production' && <Analytics />}
        <Toaster />
      </body>
    </html>
  );
}
